// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jknqmiuunghjwuyeazmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbnFtaXV1bmdoand1eWVhem1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDk2OTIsImV4cCI6MjA3MTc4NTY5Mn0.Bg5cPXGlj3s49-S-xzlAGaFipbUrwxTw8uP1Kv2weFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});